# Generated by Django 3.2.7 on 2023-09-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_collection_featured_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'Basic'), ('D', 'Diamond'), ('G', 'GOLD')], default='B', max_length=10),
        ),
    ]
